language: node_js
node_js:
  - "4.1"
  - "0.12"
addons:
  postgresql: "9.3"
services:
  - postgresql
before_script:
  - npm install -g gulp
script:
  - gulp lint
  - gulp test
after_script:
  - gulp coveralls
